### ISSUE TITLE
Memory usage after some weeks

### ISSUE THREAD

**Issue by cecchisandrone** [hanazuki/s3tftpd#3]
I'm using such image and after some weeks of usage I see that memory usage is quite huge as shown by `docker stats` command:
![image](https://user-images.githubusercontent.com/1956696/97581798-504f7a80-19f5-11eb-9e9f-d951a1ad11a8.png)
What can be causing this? I'm calling image with the following params:
```
s3tftpd:
    image: hanazuki/s3tftpd:0.4.0
    command: --anticipate 128 --blocksize=8192 --single-port --no-dualstack --verbosity 8 s3://<<bucket>>
    environment:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - AWS_REGION=eu-central-1
    restart: always
    ports:
      - "69:69/udp"
```
